### ISSUE TITLE
Bad messages for restoring a save with jet point spear wielded

### ISSUE THREAD

**Issue by demogorgon22** [demogorgon22/notdnethack#28]
" "Restoring save file... You are shrouded in a black mist! You are shrouded in a black mist! The black mist around you dissipates. You are shrouded in a black mist!""
seems to also happen with opal (handling for messaging needs to be moved)

**Comment by amateurhourrrr** [comment]
this was fixed on master by yeeting the messages entirely

**Comment by demogorgon22** [comment]
yeah i should find the commit but i dont care whatever too much work
https://github.com/demogorgon22/notdnethack/commit/cc1a73adf32ebbe8e34711eb665ee632a6e62e60
ok "fixed" here
