### ISSUE TITLE
Gillystone doesn't actually confer swimming while carried by vampire?

### ISSUE THREAD

**Issue by cosmodreamer** [demogorgon22/notdnethack#30]
Vampire can't dive underwater using ">" command.

**Comment by demogorgon22** [comment]
Nor can anybody else that flys. This would be a nice feature and the best chance of seeing it in ndnh is if you can convince dnh to implement it. Maybe one day I'll wake up with a particular rage about this in my blood and shit out a questionable implementation. It does successfully confer the swimming intrinsic though, which does things like reduce your chance of being affected by currents in water which affects them when swimming through 3d water.
