### ISSUE TITLE
"You fly down along the stairs." when ascending to the windowless tower

### ISSUE THREAD

**Issue by NetSysFire** [demogorgon22/notdnethack#31]
See https://github.com/Chris-plus-alphanumericgibberish/dNAO/issues/2008

**Comment by demogorgon22** [comment]
"fixed" in
https://github.com/demogorgon22/notdnethack/commit/a4f210e96cb68a18fcf03702da505d7695bb11f0
closing this for now until this blows up and causes issues much worse than bad messages lol :( :) :/
