### ISSUE TITLE
Actually fix bad lregion placement on certain village levels due to mazes overlapping stair placement zones or something i think

### ISSUE THREAD

**Issue by demogorgon22** [demogorgon22/notdnethack#37]
![image](https://user-images.githubusercontent.com/8377693/189541019-5456e887-23e1-4bee-85af-1cf8c17ad32d.png)
:( 
this sucks. i think it is really bad when it happens too. not sure why i havent seen it happen in a real game.

**Comment by amateurhourrrr** [comment]
after spamming the heck out of wizmakemap for a while on latest master I think this is probably fixed, have you seen it when fuzzing since then?

**Comment by demogorgon22** [comment]
haven't seen it yet but if i close it preemptively it will come back. I guess I'll do that so it can come back
