### ISSUE TITLE
The binder quest can have zombie zombies

### ISSUE THREAD

**Issue by amateurhourrrr** [demogorgon22/notdnethack#46]
Z       a zombie (zombie zombie, a medium humanoid)

Not sure if this is something specific to the binder quest, nor if it's possible in dnh

**Comment by demogorgon22** [comment]
https://github.com/demogorgon22/notdnethack/commit/796b029f54b91ae823ad9cfd7a387dbae6123573 Looks like i fixed it. Thanks!
