### ISSUE TITLE
Salamander rogue appears to never hunger

### ISSUE THREAD

**Issue by amateurhourrrr** [demogorgon22/notdnethack#48]
Currently playing a salamander rogue, and nutrition never seems to fall below 900 (seen via enlightenment)

I can stand around in gatetown just derping around, or I can even try casting spells, but I never get to weak status.

I can eat something and immediately become satiated, but nutrition correctly falls as normal back down to 900 where it decreases no further.

**Comment by demogorgon22** [comment]
https://github.com/demogorgon22/notdnethack/commit/941fe223f5d73183c6bbf590c0e1e102e00abc53 thanks it looks like i fixed this. Good catch.
