### ISSUE TITLE
The psionic pulse misses the monster.  The monster is thrown backwards by the force of your pulse!

### ISSUE THREAD

**Issue by NetSysFire** [demogorgon22/notdnethack#50]
You obviously need to be an acu for this.

If the pulse misses a monster, it should not throw it backwards. Alternatively a different message would also work if it is intended to throw other monsters backwards.

**Comment by demogorgon22** [comment]
I think i fixed this. I seem to remember fixing this.  Ok i found it. https://github.com/demogorgon22/notdnethack/commit/88bea47def08d6d9c23eafb4f6eefbb0632b588b Thanks!
