### ISSUE TITLE
You eat Warmachine's brain!  Warmachine's last thought fades away...

### ISSUE THREAD

**Issue by NetSysFire** [demogorgon22/notdnethack#52]
Tbh not sure if Warmachine is actually susceptible to int drain. In that case it was very low on HP and my tentacle attack may have killed it outright.

**Comment by demogorgon22** [comment]
https://github.com/demogorgon22/notdnethack/commit/b25e265d4fbfb97fafe574b30ce517f5cd439fc3 Looks like i fixed this. good catch.
