### ISSUE TITLE
You can change out spearheads if straitjacketed

### ISSUE THREAD

**Issue by NetSysFire** [demogorgon22/notdnethack#62]
Steps to reproduce:

1. Start as a madman.
2. Find a spear.
3. Apply it.

Although in my case I found a +1 atgeir, drained it (as an incantifier) and it was disassembled into a tipless atgeir and a gray stone spearhead, making them significantly more useless in that corner case.

**Comment by demogorgon22** [comment]
Dude what why would it even do that. not cool. stupid code change. also atgeir shouldn't even be a tipped spear :( so many bugs here. thanks.

**Comment by demogorgon22** [comment]
https://github.com/demogorgon22/notdnethack/commit/058827206eec2be9d519113d7b188f87d7e32585 fixed
