### ISSUE TITLE
First Wraithworm can not spawn

### ISSUE THREAD

**Issue by demogorgon22** [demogorgon22/notdnethack#8]
Does it not always? idk. my test as a barb human, it wasnt there. Where is it?

**Comment by demogorgon22** [comment]
sike i was a priest human

**Comment by amateurhourrrr** [comment]
upstream issue: https://github.com/Chris-plus-alphanumericgibberish/dNAO/pull/1908

**Comment by amateurhourrrr** [comment]
This should now be fixed on master :)
