### ISSUE TITLE
Show tattoos in #attributes

### ISSUE THREAD

**Issue by NetSysFire** [demogorgon22/notdnethack#98]
So they can be shown on game end and enlightenment too and are not effectively invisible

**Comment by demogorgon22** [comment]
Added to enlightenment, not attributes. knowing what is on  your own skin in this game may require a deeper level of knowledge than self inspection, idk. https://github.com/demogorgon22/notdnethack/commit/99fe26082527b211987d01f5f39c0ddaea120e93
