### ISSUE TITLE
Astral vision exceeding width of the map

### ISSUE THREAD

**Issue by baoliejuan** [demogorgon22/notdnethack#99]
If you are a max level Etherealoid monk wearing Eye of the Overworld and have Orthos bound, weird thing would happen, you only see some rows of the map instead of the entire map

**Comment by demogorgon22** [comment]
I was afraid this would occur. I know that if a permalight call uses a radius bigger than the map, it crashes. I tested briefly to validate that xray didnt crash, it seemed to not be broken, and so I called it good. I guess it is broken though? I will have to investigate further. Thanks.

**Comment by demogorgon22** [comment]
https://github.com/demogorgon22/notdnethack/commit/d145259273192b4a7eae3ffd1726719265511059 fixes
